#!/usr/bin/bash

N=$(nproc --all)
touch fst.txt
touch perf.csv
echo "Number of threads; Number of execution; Time elapsed" >> fst.csv
for i in {1 .. N}
do
    for j in {1 ... 5}
    do
    echo "$i; $j; $(/usr/bin/time -f %e make -j $i -s)" &>> perf.csv
    done
done
grep -vwE "(ar)" fst.txt >> perf.csv
rm fst.txt



